@startuml MER
class Tarefa {
  +id: int
  +titulo: String
  +descricao: String
  +dataHoraCriacao: DateTime
  +status: String
}

class Categoria {
  +id: int
  +nome: String
}

class Usuario {
  +id: int
  +nome: String
  +email: String
  +senha: String
}

Tarefa --> Categoria : "1..1"
Tarefa --> Usuario : "1..*"
@enduml
