@startuml MER

entity "Usuarios" as usuarios {
    + id: UUID
    --
    nome: string
    email: string
    senha: string
    created_at: datetime
}

entity "Tarefas" as tarefas {
    + id: UUID
    --
    titulo: string
    descricao: text
    status: enum("Pendente", "Em andamento", "Concluído")
    categoria_id: UUID
    usuario_id: UUID
    completed_at: datetime
    created_at: datetime
}

entity "Categorias" as categorias {
    + id: UUID
    --
    nome: enum("Casa", "Estudos", "Lazer", "Mercado", "Contas", "Outros")
    created_at: datetime
}

usuarios ||--o{ tarefas
categorias ||--o{ tarefas

@enduml

